import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';

// Use Inter font
const inter = Inter({
  variable: '--font-inter',
  subsets: ['latin'],
  weight: ['400', '500', '600', '700', '800', '900'], // optional: define weights you need
});

export const metadata: Metadata = {
  title: 'Victoria College',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} bg-navy-dark w-screen overflow-x-hidden py-14 antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
